"use client"

import { useState } from "react"
import { PlusIcon } from "lucide-react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"

import { PageHeader } from "@/components/page-header"
import { Button } from "@/components/ui/button"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog"

import {
  createBlogCategoryAction,
  deleteBlogCategoryAction,
  updateBlogCategoryAction,
} from "../actions/blog-categories"
import type {
  BlogCategoryDetails,
  BlogCategoryRow,
} from "../queries/blog-categories"
import { BlogCategoryFormDialog } from "./blog-category-form-dialog"
import { BlogCategoriesTable } from "./blog-categories-table"

type BlogCategoriesPageProps = {
  categories: BlogCategoryRow[]
  defaultCreateOpen?: boolean
  defaultEditCategory?: BlogCategoryDetails | null
  closeDestination?: string
}

export function BlogCategoriesPage({
  categories,
  defaultCreateOpen = false,
  defaultEditCategory = null,
  closeDestination,
}: BlogCategoriesPageProps) {
  const router = useRouter()
  const [createOpen, setCreateOpen] = useState(defaultCreateOpen)
  const [editingCategory, setEditingCategory] = useState<BlogCategoryDetails | null>(
    defaultEditCategory,
  )
  const [deleteTarget, setDeleteTarget] = useState<BlogCategoryRow | null>(null)

  async function handleCreate(values: {
    name: string
    description: string
  }) {
    return createBlogCategoryAction(values)
  }

  async function handleUpdate(values: {
    name: string
    description: string
  }) {
    if (!editingCategory) {
      return {
        success: false as const,
        message: "No blog category is currently selected.",
      }
    }

    return updateBlogCategoryAction(editingCategory.id, values)
  }

  async function handleDelete() {
    if (!deleteTarget) {
      return
    }

    const result = await deleteBlogCategoryAction(deleteTarget.id)

    if (result.success) {
      toast.success("Blog category deleted.")
      setDeleteTarget(null)

      if (closeDestination) {
        router.push(closeDestination)
      } else {
        router.refresh()
      }
      return
    }

    toast.error(result.message)
    setDeleteTarget(null)
  }

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Blog Categories"
        subtitle="Manage editorial categories, autogenerated slugs, and aggregated blog analytics from one academic admin workspace."
        actions={
          <Button
            type="button"
            onClick={() => setCreateOpen(true)}
            className="shadow-sm shadow-primary/15"
          >
            <PlusIcon data-icon="inline-start" />
            Create Category
          </Button>
        }
      />

      <BlogCategoriesTable
        data={categories}
        onEdit={setEditingCategory}
        onDelete={setDeleteTarget}
      />

      <BlogCategoryFormDialog
        open={createOpen}
        mode="create"
        title="Create Blog Category"
        description="Create a new blog category."
        submitLabel="Create category"
        onOpenChange={(open) => {
          setCreateOpen(open)

          if (!open && closeDestination && defaultCreateOpen) {
            router.push(closeDestination)
          }
        }}
        onSubmit={handleCreate}
        onSuccess={async () => {
          toast.success("Blog category created.")
          setCreateOpen(false)

          if (closeDestination && defaultCreateOpen) {
            router.push(closeDestination)
            return
          }

          router.refresh()
        }}
      />

      <BlogCategoryFormDialog
        open={Boolean(editingCategory)}
        mode="edit"
        title="Edit Blog Category"
        description="Update the category name or description. The slug stays automatic and unique from the name."
        submitLabel="Save changes"
        initialValues={
          editingCategory
            ? {
                name: editingCategory.name,
                description: editingCategory.description ?? "",
              }
            : undefined
        }
        onOpenChange={(open) => {
          if (!open) {
            setEditingCategory(null)

            if (closeDestination && defaultEditCategory) {
              router.push(closeDestination)
            }
          }
        }}
        onSubmit={handleUpdate}
        onSuccess={async () => {
          toast.success("Blog category updated.")
          setEditingCategory(null)

          if (closeDestination && defaultEditCategory) {
            router.push(closeDestination)
            return
          }

          router.refresh()
        }}
      />

      <AlertDialog
        open={Boolean(deleteTarget)}
        onOpenChange={(open) => {
          if (!open) {
            setDeleteTarget(null)
          }
        }}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete blog category?</AlertDialogTitle>
            <AlertDialogDescription>
              This action cannot be undone. The category will only be deleted if it
              has no blog posts attached to it.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel asChild>
              <Button type="button" variant="outline">
                Cancel
              </Button>
            </AlertDialogCancel>
            <AlertDialogAction asChild>
              <Button type="button" variant="destructive" onClick={() => void handleDelete()}>
                Delete
              </Button>
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}
